//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RFRM.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_OK                          102
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_RFRMTYPE                    129
#define IDB_BITMAP_LIST                 129
#define ID_INDICATOR_TAG_COUNT          129
#define ID_INDICATOR_COUNT              129
#define IDB_BITMAP_24                   130
#define ID_INDICATOR_TAG_CLEAR          130
#define ID_INDICATOR_CLEAR              130
#define IDC_CLEAR_BUTTON                131
#define IDB_BITMAP_16                   132
#define ID_INDICATOR_COUNT_EDIT         132
#define IDD_DIALOG1                     133
#define IDS_NOITEMSEL                   133
#define ID_TAG_TOTAL_READ_COUNT         133
#define IDR_MENU_LIST                   134
#define IDS_SELFORINFO                  134
#define IDS_LC_ID                       134
#define IDS_LC_PC                       135
#define IDD_DIALOG_SPLASH               136
#define IDS_LC_TOTALCOUNT               136
#define IDS_LC_READCOUNT                137
#define IDB_BITMAP_SPLASH               138
#define IDS_LC_TRIALCOUNT               138
#define IDS_LC_ANTENNA                  139
#define IDD_DIALOG_SETTING              140
#define IDD_DIALOG_GENERAL              140
#define IDS_LC_CHANNEL                  140
#define IDB_BITMAP_36                   141
#define IDS_LC_RSSI                     141
#define IDD_DIALOG_ANTENNA              142
#define IDS_LC_LNAGAIN                  142
#define IDS_LC_RECEIVETIME              143
#define IDS_CLEAR_BUTTON                144
#define IDS_STRING_RFID_STATUS_OK       145
#define IDB_FOLDERS                     146
#define IDS_STRING_RFID_ERROR_ALREADY_OPEN 146
#define IDS_STRING_RFID_ERROR_BUFFER_TOO_SMALL 147
#define IDS_STRING_RFID_ERROR_CURRENTLY_NOT_ALLOWED 148
#define IDD_DIALOG_ANTENNA_EDIT         149
#define IDS_STRING_RFID_ERROR_FAILURE   149
#define IDR_MENU_TAG_ACCESS             150
#define IDS_STRING_RFID_ERROR_DRIVER_LOAD 150
#define IDD_DIALOG_ENGINEERING          151
#define IDS_STRING_RFID_ERROR_DRIVER_MISMATCH 151
#define IDS_STRING_RFID_ERROR_EMULATION_MODE 152
#define IDS_STRING_RFID_ERROR_INVALID_ANTENNA 153
#define IDB_BITMAP_TAB_32               154
#define IDS_STRING_RFID_ERROR_INVALID_HANDLE 154
#define IDB_BITMAP_TAB_16               155
#define IDS_STRING_RFID_ERROR_INVALID_PARAMETER 155
#define IDD_DIALOG_TAG_ACCESS_READ      156
#define IDS_STRING_RFID_ERROR_NO_SUCH_RADIO 156
#define IDD_DIALOG_TAG_ACCESS_WRITE     157
#define IDS_STRING_RFID_ERROR_NOT_INITIALIZED 157
#define IDD_DIALOG_SELECT_CRITERIA      158
#define IDS_STRING_RFID_ERROR_NOT_SUPPORTED 158
#define IDD_DIALOG_ALGORITHM            159
#define IDS_STRING_RFID_ERROR_OPERATION_CANCELLED 159
#define IDD_DIALOG_POST_SINGULATION     160
#define IDS_STRING_RFID_ERROR_OUT_OF_MEMORY 160
#define IDD_DIALOG_INTERFACE            161
#define IDS_STRING_RFID_ERROR_RADIO_BUSY 161
#define IDR_INFO_TOOLBAR                162
#define IDS_STRING_RFID_ERROR_RADIO_FAILURE 162
#define IDS_STRING_RFID_ERROR_RADIO_NOT_PRESENT 163
#define IDB_BITMAP_TOOLBAR              164
#define IDB_BITMAP_TOOLBAR_COLOR        164
#define IDB_BITMAP_TOOLBAR_COLOR_16     164
#define IDS_STRING_RFID_ERROR_RADIO_NOT_RESPONDING 164
#define IDS_STRING_RFID_ERROR_NONVOLATILE_INIT_FAILED 165
#define IDB_BITMAP_TOOLBAR_GRAY         166
#define IDB_BITMAP_TOOLBAR_GRAY_16      166
#define IDS_STRING_RFID_ERROR_NONVOLATILE_OUT_OF_BOUNDS 166
#define IDB_BITMAP_TOOLBAR_GRAY_32      167
#define IDS_STRING_RFID_ERROR_NONVOLATILE_WRITE_FAILED 167
#define IDB_BITMAP_TOOLBAR_COLOR_32     168
#define IDS_STRING_RFID_ERROR_UNKNOWN   168
#define IDB_BITMAP_INFO_TOOLBAR_GRAY_32 169
#define IDS_STRING_POWER_OFF            169
#define IDB_BITMAP_INFO_TOOLBAR_COLOR_32 170
#define IDS_STRING_POWER_ON             170
#define IDB_BITMAP_INFO_TOOLBAR_COLOR_16 171
#define IDS_STRING_RFID_STOP_SUCCESS    171
#define IDB_BITMAP_INFO_TOOLBAR_GRAY_16 172
#define IDS_STRING_RFID_STOP_FAIL       172
#define IDD_DIALOG_SERVER_IP            173
#define IDS_STRING_INVENTORY            173
#define IDS_STRING_RFID_POWER_ON        174
#define IDS_STRING_RFID_POWER_OFF       175
#define IDD_DIALOG_COUNT                176
#define IDS_STRING_TAGACCESS_ERROR_01   176
#define IDR_TOOLBAR_TAGACCESS           177
#define IDS_STRING_TAGACCESS_ERROR_02   177
#define IDS_STRING_TAGACCESS_ERROR_03   178
#define IDB_BITMAP_TAG_ACCESS_COLOR_32  179
#define IDS_STRING_TAGACCESS_ERROR_04   179
#define IDB_BITMAP_TAG_ACCESS_GRAY_32   180
#define IDS_STRING_TAGACCESS_ERROR_05   180
#define IDD_DIALOG_FIRMWARE_OPTION      181
#define IDS_STRING_TAGACCESS_ERROR_06   181
#define IDD_DIALOG_FIRMWARE_STATUS      182
#define IDS_STRING_TAGACCESS_ERROR_07   182
#define IDD_DIALOG_TAG_ACCESS_LOCK      183
#define IDS_STRING_TAGACCESS_ERROR_0A   183
#define IDD_DIALOG_TAG_ACCESS_KILL      184
#define IDS_STRING_TAGACCESS_ERROR_0B   184
#define IDS_STRING_TAGACCESS_ERROR_0C   185
#define IDS_STRING_TAGACCESS_ERROR_0D   186
#define IDS_STRING_TAGACCESS_BACKSCATTER_00 187
#define IDS_STRING_TAGACCESS_BACKSCATTER_03 188
#define IDS_STRING_TAGACCESS_BACKSCATTER_04 189
#define IDS_STRING_TAGACCESS_BACKSCATTER_0B 190
#define IDS_STRING_TAGACCESS_BACKSCATTER_0F 191
#define IDD_DIALOG_RFBAND               300
#define IDD_DIALOG_FREQUENCY_BAND       300
#define IDC_STATIC_MAC_VERSION          1000
#define IDC_EDIT1                       1004
#define IDC_EDIT_POWER                  1004
#define IDC_EDIT_TRANSFER_TIME          1004
#define IDC_EDIT_EPC                    1004
#define IDC_EDIT_MIN_Q                  1005
#define IDC_EDIT_BEEP_FILE_PATH         1005
#define IDC_EDIT_KILL_PASSWORD          1005
#define IDC_EDIT_PHY_TX                 1006
#define IDC_EDIT_MAX_TRIAL_COUNT        1006
#define IDC_EDIT_DATA0                  1006
#define IDC_EDIT_MAX_Q                  1006
#define IDC_EDIT_WRITE_DATA             1006
#define IDC_SPIN_PHYSICAL_PORT          1007
#define IDC_SPIN_TX_PHYSICAL_PORT       1007
#define IDC_SPIN_POWER                  1007
#define IDC_SPIN_RX_PHYSICAL_PORT       1008
#define IDC_SPIN_PHY_TX                 1008
#define IDC_SPIN_MIN_Q                  1008
#define IDC_SPIN_DWELL                  1009
#define IDC_SPIN_MAX_Q                  1009
#define IDC_STATIC_STATUS               1010
#define IDC_EDIT_RETRY_COUNT            1010
#define IDC_SPIN_INV_CYCLE              1011
#define IDC_SPIN_RETRY_COUNT            1011
#define IDC_COMBO1                      1013
#define IDC_COMBO_REGION                1013
#define IDC_COMBO_STATE                 1013
#define IDC_COMBO_MBANK                 1013
#define IDC_COMBO_ALGORITHM             1013
#define IDC_COMBO_INTERFACE             1013
#define IDC_COMBO_REGION2               1014
#define IDC_COMBO_LINK_PROFILE          1014
#define IDC_LIST1                       1014
#define IDC_LIST_ANTENNA                1014
#define IDC_COMBO_SELECT_STATE          1014
#define IDC_COMBO_ACCESS_PASSWORD_PERMISSION 1014
#define IDC_LIST_RFBAND                 1014
#define IDC_LIST_FREQUENCY_BAND         1014
#define IDC_COMBO_DATA_FORMAT           1015
#define IDC_EDIT_DWELL                  1015
#define IDC_COMBO_SESSION               1015
#define IDC_COMBO_EPC_BANK_PERMISSION   1015
#define IDC_COMBO_LINK_PROFILE3         1016
#define IDC_COMBO_OPERATION_MODE        1016
#define IDC_EDIT_INV_CYCLE              1016
#define IDC_COMBO_SESSION2              1016
#define IDC_COMBO_TOGGLE_TARGET         1016
#define IDC_COMBO6                      1016
#define IDC_COMBO_TID_BANK_PERMISSION   1016
#define IDC_BUTTON_EDIT_ANTENNA         1017
#define IDC_SPIN_THRESHOLD              1017
#define IDC_BUTTON_WAVE_PATH            1017
#define IDC_BUTTON_BEEP_FILE_PATH       1017
#define IDC_COMBO_USER_BANK_PERMISSION  1017
#define IDC_COMBO_INVENTORY_ALGORITHM   1018
#define IDC_COMBO_OFFSET                1018
#define IDC_COMBO_SESSION_TARGET        1018
#define IDC_COMBO_SESSION3              1019
#define IDC_COMBO_REPETE_UNTILE_NO_TAGS 1019
#define IDC_COMBO_BEEP                  1019
#define IDC_COMBO_BEEP_MODE             1019
#define IDC_CHECK_CARRIER_ON_OFF        1020
#define IDC_EDIT_QVALUE                 1020
#define IDC_EDIT_Q_VALUE                1020
#define IDC_COMBO_COUNT                 1021
#define IDC_SPIN_QVALUE                 1021
#define IDC_SPIN_DISPLAY_CRITERION      1022
#define IDC_EDIT_MAX_QUERY_REPS         1022
#define IDC_SCROLLBAR_ALGORITHM         1023
#define IDC_SPIN_MAX_QUERY_REPS         1024
#define IDC_STATIC_START_Q              1025
#define IDC_STATIC_MIN_Q                1026
#define IDC_STATIC_MAX_Q                1027
#define IDC_STATIC_RETRY_COUNT          1028
#define IDC_STATIC_TOGGLE               1029
#define IDC_STATIC_TOGGLE_TARGET        1029
#define IDC_STATIC_THRESHOLD            1030
#define IDC_EDIT_START_Q                1031
#define IDC_SPIN_START_Q                1032
#define IDC_EDIT_THRESHOLD_MULTIPLIER   1033
#define IDC_CHECK_LEAK_CONT             1033
#define IDC_SPIN_THRESHOLD_MULTIPLIER   1034
#define IDC_EDIT_ADDRESS                1037
#define IDC_EDIT_PORT                   1038
#define IDC_EDIT_IPADDRESS              1039
#define IDC_CHECK_SESSION0              1040
#define IDC_CHECK_SESSION1              1041
#define IDC_CHECK_SESSION2              1042
#define IDC_CHECK_SESSION3              1043
#define IDC_EDIT_COUNT_LARGE            1043
#define IDC_RADIO_UPDATE_ALL            1044
#define IDC_RADIO_TEST_MODE_ONLY        1045
#define IDC_RADIO_SKIP_TEST_MODE        1046
#define IDC_PROGRESS1                   1047
#define IDC_STATIC_RESULT               1048
#define IDC_STATIC_TIMER                1049
#define IDC_RADIO_EPC_DISPLAY           1051
#define IDC_RADIO_ASCII_DISPLAY         1052
#define IDC_STATIC_PRODUCT_VER          1052
#define IDC_STATIC_PRODUCT_VERSION      1052
#define IDC_EDIT_ACCESS_PASSWORD        1053
#define IDC_COMBO_KILL_PASSWORD_PERMISSION 1054
#define ID_RFID_STARTUP                 32771
#define ID_RFID_SHUTDOWN                32772
#define ID_RFID_MACVERSION              32773
#define ID_RFID_ANTENNAEDIT             32775
#define ID_LIST_ICON                    32776
#define ID_LIST_LIST                    32777
#define ID_LIST_REPORT                  32778
#define ID_LIST_SMALL                   32779
#define ID_LIST_SMALL_ICON              32780
#define ID_RFID_RADIOOPEN               32781
#define ID_RFID_RADIOCLOSE              32782
#define ID_RFID_POWERRESET              32783
#define ID_RFID_POWER                   32784
#define ID_RFID_STOP                    32785
#define ID_RFID_START                   32786
#define ID_RFID_READERSETTING           32787
#define ID_RFID_READERSET               32788
#define ID_RFID_READER_SET              32789
#define ID_FILE_POWER                   32790
#define ID_FILE_RESET                   32791
#define ID_FILE_POWER_ON_OFF            32792
#define ID_RFID_POWER_ON_OFF            32794
#define ID_RFID_RESET                   32795
#define ID_RFID_CONNECTION              32796
#define ID_RFID_DISCONNECTION           32797
#define ID_RFID_RUN_INVENTORY           32798
#define ID_RFID_STOP_INVENTORY          32799
#define ID_TAG_READ                     32800
#define ID_TAG_WRITE                    32801
#define ID_TAG_LOCK                     32802
#define ID_TAG_KILL                     32803
#define ID_RFID_STOP_INVENTORY2         32804
#define ID_READ_TOTAL_COUNT             32809
#define ID_LEAK_CHECK                   32810
#define ID_LEAK_TIME                    32811
#define ID_RFID_INTERFACECONFIGURATION  32812
#define ID_RFID_SERVERCONNECTION        32813
#define ID_RFID_SERVERCONNECT           32814
#define ID_RFID_INVENTORYONCE           32815
#define ID_RFID_INVENTORY_ONCE          32816
#define ID_FILE_EXPORT                  32817
#define ID_EDIT_LISTVIEW                32823
#define ID_EDIT_TOTALCOUNTVIEW          32824
#define ID_EDIT_UNIQUECOUNTVIEW         32825
#define ID_RFID_INVENTORY               32826
#define ID_RFID_FIRMWARE                32827
#define ID_FIRMWARE_UPDATEOPTION        32828
#define ID_FIRMWARE_UPDATE              32829
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_VERSION            59143
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_HELP                        65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007
#define IDS_EDIT                        65010
#define IDS_TOOL                        65011
#define IDM_MENU                        65012
#define IDR_MAIN_EDIT                   65013
#define IDR_MAIN_TOOL                   65014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
